python3 othello.py -l
python3 othello.py -l
python3 othello.py -l
python3 othello.py -l
python3 othello.py -l
python3 othello.py -l
python3 othello.py -l
python3 othello.py -l
python3 othello.py -l
python3 othello.py -l
